---
title: "Analysis Package Layout"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Analysis Package Layout}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

R Analysis Packages are an extension of the standard R package layout designed to support publishing a collection of R notebooks used for data analysis as static html, typically using [GitHub Pages](https://pages.github.com).

[R Notebooks](https://bookdown.org/yihui/rmarkdown/notebook.html) include a YAML header and [R Markdown](https://github.com/rstudio/rmarkdown) body. The Analysis Package Layout follows the convention that the first non-blank line in the body of an R notebook serves as a brief description of the work. `rdev` includes an "Analysis Notebook" RStudio R Markdown template (File > New File > Rmarkdown > From Template) and a `README.Rmd` template optionally installed with `use_analysis_package()` that dynamically builds a list of notebooks and descriptions when [`devtools:build_readme()`](https://devtools.r-lib.org/reference/build_rmd.html) is run.

Starting in version 1.8.0, rdev also supports publishing Analysis Notebooks using [Quarto](https://quarto.org) as an alternative to the original `use_analysis_package()`.

The table below documents the complete R Analysis Package layout:

- **Path**: Path to the file or directory relative to the package root
- **R**: Included in the R package definition
- **g**: Stored in git
- **Function**: The function of the file or directory

Path                     | R | g | Function
:------------------------|:--|:--|:-----------------------------------------------------------------------------------------------------------------------------------------------------
.Rbuildignore            |   |`x`| Files excluded from the package, sorted using `sort_rbuildignore()`
.RData                   |   |   | Saved workspace - not used
.Rhistory                |   |   | R command history
.Rprofile                |   |`x`| Used by `renv` and to [attach development tools](https://r-pkgs.org/setup.html?#personal-startup-configuration) and set project options
.Rproj.user              |   |   | RStudio local project files
.git                     |   |   | git version control
.github                  |   |`x`| GitHub templates and workflows
.gitignore               |   |`x`| git exclusions based on [GitHub R](https://github.com/github/gitignore/blob/master/R.gitignore). Generated files outside of `docs` (used by GitHub Pages) are excluded.
.lintr                   |   |`x`| [lintr](https://lintr.r-lib.org/index.html) configuration as described in the Style Guide, `vignette("style-guide")`
.nojekyll                |   |`x`| [Disable](https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/) Jekyll processing on [GitHub Pages](https://pages.github.com)
.quarto                  |   |   | Used by [Quarto](https://quarto.org)
DESCRIPTION              |`x`|`x`| Package metadata. Use "Suggests" for development tools, per [renv](https://rstudio.github.io/renv/articles/faq.html#how-should-i-handle-development-dependencies-)
LICENSE                  |`x`|`x`| Generated with `usethis::use_mit_license()`
LICENSE.md               |   |`x`| See above, used by [pkgdown](https://pkgdown.r-lib.org) and [Quarto](https://quarto.org)
NAMESPACE                |`x`|`x`| Automatically generated with [roxygen2](https://roxygen2.r-lib.org)
NEWS.md                  |`x`|`x`| Release notes, used by `get_release()`, [pkgdown](https://pkgdown.r-lib.org) and [Quarto](https://quarto.org)
R                        |`x`|`x`| All project functions go here, with [roxygen2](https://roxygen2.r-lib.org) comments
README.Rmd               |   |`x`| Generated with `usethis::use_readme_md()` or rdev template
README.md                |`x`|`x`| Generated with `devtools::build_readme()`
TODO.md                  |`x`|`x`| To-do list, inspired by renv's [historical TODO.md](https://github.com/rstudio/renv/blob/99737730ea69730b211770ba2bfa78301cf0e7b2/TODO.md)
_freeze                  |   |`x`| Used by the Quarto [`freeze`](https://quarto.org/docs/projects/code-execution.html#freeze) option
_pkgdown.yml             |   |`x`| [pkgdown](https://pkgdown.r-lib.org) metadata, stored in the project root to make it more [discoverable](https://github.com/search?q=filename%3Apkgdown.yml+path%3A%2F&type=Code) (not used with Quarto)
_quarto.yml              |`x`|`x`| Quarto [configuration file](https://quarto.org/docs/projects/quarto-projects.html#project-metadata)
analysis                 |`x`|`x`| Exploratory data analysis in R Notebooks and R Presentations. Include functions from the R directory using `library()`, not `source()`.
analysis/_metadata.yml   |`x`|`x`| Quarto [directory configuration file](https://quarto.org/docs/projects/quarto-projects.html#directory-metadata)
analysis/assets          |`x`|`x`| External assets (images, other files) included in R Notebooks
analysis/data            |`x`|`x`| Used to store small data sets used for analysis and exported data as `csv` files
analysis/import          |   |   | Used for local storage of large data sets
analysis/rendered        |   |   | Manually rendered versions of `analysis/` files to be included in `docs/`, like [.Rpres files](https://stackoverflow.com/questions/27930127/render-r-presentation-from-the-command-line)
changelog.qmd            |`x`|`x`| Quarto front-end to NEWS.md
demos                    |`x`|   | Not used, as recommended by [R Packages](https://r-pkgs.org/misc.html)
docs                     |   |`x`| Used by `build_analysis_site()` and `build_quarto_site()` to render the R Package and Notebooks for GitHub Pages
exec                     |`x`|   | Command line executable scripts - not used
index.qmd                |`x`|`x`| Quarto home page, using the [listing page](https://quarto.org/docs/websites/website-listings.html) format
inst                     |`x`|`x`| Installed files: templates and [WORDLIST](https://docs.ropensci.org/spelling/reference/wordlist.html)
inst/bin                 |`x`|`x`| Used for shell scripts that support development, like `setup-r`
inst/rmarkdown/templates |`x`|`x`| [R Markdown Templates](https://rstudio.github.io/rstudio-extensions/rmarkdown_templates.html)
man                      |`x`|`x`| Automatically generated with [roxygen2](https://roxygen2.r-lib.org)
package.Rproj            |   |`x`| Use the same name for the package, .Rproj, directory, and GitHub repository
pkgdown                  |   |`x`| Store all [pkgdown](https://pkgdown.r-lib.org) files here (not used with Quarto)
po                       |`x`|`x`| Used for [Internationalization](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Internationalization) if needed
renv                     |   |`x`| Used by [renv](https://rstudio.github.io/renv/)
renv.lock                |   |`x`| renv [lockfile](https://rstudio.github.io/renv/reference/lockfiles.html)
tests                    |`x`|`x`| Tests using [testthat](https://testthat.r-lib.org) and [spelling](https://docs.ropensci.org/spelling/)
tools                    |`x`|   | Auxiliary files needed for building packages - not used
vignettes                |`x`|`x`| Package vignettes and articles, written in R Markdown
