#!/bin/sh
# uses https://github.com/gjtorikian/html-proofer
# install with:
# $ gem update --system
# $ gem install html-proofer
set -ex # halt script on error, echo on

htmlproofer docs --check-html --check-img-http --check-opengraph --allow-hash-href --empty-alt-ignore true \
	--report-invalid-tags --report-missing-names --report-script-embeds --report-missing-doctype --report-eof-tags \
	--report-mismatched-tags \
	--http-status-ignore 403,503 $*
