# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: missing-deps

permissions: read-all

jobs:
  missing-deps:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: r-lib/actions/setup-r@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4

      - uses: r-lib/actions/setup-renv@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4

      - name: Install rdev for rdev
        run: |
          if (!requireNamespace("rdev", quietly = TRUE)) { # only TRUE for rdev itself
            remotes::install_local(".", upgrade = "never")
          }
        shell: Rscript {0}

      - name: Find missing dependencies
        run: |
          mdeps <- rdev::missing_deps()
          mdeps
          stopifnot(nrow(mdeps) == 0)
        shell: Rscript {0}
